//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expens()
        {
            this.Supervisors = new HashSet<Supervisor>();
        }
    
        public int ReceiptNumber { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<System.DateTime> ReceiptSubmittedDate { get; set; }
        public Nullable<decimal> ReceiptAmount { get; set; }
        public byte[] UploadReceipt { get; set; }
        public string Status { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> SupervisorId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Supervisor Supervisor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supervisor> Supervisors { get; set; }
    }
}
