//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supervisor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supervisor()
        {
            this.Expenses = new HashSet<Expens>();
        }
    
        public int SupervisorId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ReceiptNumber { get; set; }
        public string SupervisorName { get; set; }
        public string Approve_Reject { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string EmailID { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expens> Expenses { get; set; }
        public virtual Expens Expens { get; set; }
    }
}
